# circle ci configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.12
      # - image: shuhaozhang/auction-svc:latest
      #   auth:
      #     username: $DOCKERUSERNAME
      #     password: $DOCKERPASSWORD
    steps:
      - checkout
      - run:
          name: Deploy and Run Application
          command:  |
            docker login -u $DOCKERUSERNAME -p $DOCKERPASSWORD
            docker pull shuhaozhang/auction-svc:latest
            docker run -d -p 7001:80 shuhaozhang/auction-svc:latest
            sleep 10

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
