version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore src/AuctionService

      - run:
          name: Build and Watch AuctionService
          command: dotnet watch --project src/AuctionService run

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore src/AuctionService

      - run:
          name: Run Unit Tests
          command: dotnet test tests/AuctionService.UnitTest

      - run:
          name: Run Integration Tests
          command: dotnet test tests/AuctionService.IntegrationTest

  docker-compose-setup:
    docker:
      - image: docker:latest
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            apk --update add docker-compose
            docker-compose --version

      - run:
          name: Run Docker Compose for Dependencies
          command: docker-compose -f Carties/docker-compose.yml up -d

workflows:
  version: 2
  build-and-test:
    jobs:
      - docker-compose-setup
      - build:
          requires:
            - docker-compose-setup
      - test:
          requires:
            - build