version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build and Watch AuctionService
          command: dotnet watch src/AuctionService run

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Run Unit Tests
          command: dotnet test tests/AuctionService.UnitTest

      - run:
          name: Run Integration Tests
          command: dotnet test tests/AuctionService.IntegrationTest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build