# circle ci configuration file
version: 2.1
# orbs:
#   docker: circleci/docker@1.4.0
jobs:
  build:
    docker:
      - image: cimg/base:2023.12
      - image: shuhaozhang/auction-svc:latest
        auth:
          username: $DOCKERUSERNAME
          password: $DOCKERPASSWORD
    steps:
      - checkout
      - run:
          name: Run Application
          command: |
            docker run -d -p 7001:80 shuhaozhang/auction-svc:latest
      # - docker/check:
      #     docker-username: $DOCKERUSERNAME
      #     docker-password: $DOCKERPASSWORD
      # - docker/pull:


workflows:
  version: 2
  build_and_run:
    jobs:
      - build
