# circle ci configuration file
version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
        auth:
          username: $DOCKERUSERNAME
          password: $DOCKERPASSWORD
    working_directory: /app

    steps:
      - checkout
      - run:
          name: Deploy and Run Application
          command:  |
            docker pull shuhaozhang/auction-svc:latest
            docker run -d -p 7001:80 shuhaozhang/auction-svc:latest
            sleep 10

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
